name: build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'

      - name: build image
        run: |
          docker build \
          -t muktiarafi/ticketing-expiration:latest \
          -t muktiarafi/ticketing-expiration:$GITHUB_SHA \
          .

      - name: push
        run: |
          docker push muktiarafi/ticketing-expiration:latest
          docker push muktiarafi/ticketing-expiration:$GITHUB_SHA
